version: "3"

services:

  app:
    build:
      context: ./.docker/build/app
    volumes:
      - ./:/var/www/
    command: npm run dev
    environment:
      - PORT=3001

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: app
    volumes:
      - .docker/data/mongo:/data/db
      - .docker/config/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mock:
    image: muonsoft/openapi-mock
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/var/www/swagger.json'
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    tty: true
