#!/bin/sh

set -e


# Try to fix code style
docker compose exec -T app npm run prettier:fix

# Validate code with Prettier
docker compose exec -T app npm run prettier

# Run tests
docker compose exec -T app npm test