#!/bin/sh

# Validate code with Prettier
docker-compose exec -T app npm run prettier
prettier_result=$?

# Try to fix code style
docker-compose exec -T app npm run prettier:fix

# Run tests
if [ $prettier_result -eq 0 ]; then
  docker-compose exec -T app npm run test
fi
