definitions:
  KudosRequest:
    type: object
    required:
      - panelSlug
      - title
      - description
      - from
      - to
    properties:
      panelSlug:
        type: string
        example: "panel123"
      title:
        type: string
        example: "Kudos Title"
      description:
        type: string
        example: "Kudos Description"
      from:
        type: string
        example: "Kudos Author"
      to:
        type: string
        example: "Kudos Receiver"